<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 15/10/2018
 * Time: 11:58 AM
 */

class user_login{

    function registration($conn){

        if (!isset($_POST['username'])){
            echo "No name found";
        }elseif (!$_POST['mobile']){
            echo "No mobile number found";
        }elseif (!$_POST['email']){
            echo "No email found";
        }elseif (!$_POST['voucher']){
            echo "No voucher found";
        }elseif (!$_POST['password']){
            echo "No voucher found";
        }else{

            $index = $_POST['username'];
            $username = $_POST['username'];
            $password = $_POST['password'];
            $mobile = $_POST['mobile'];
            $email = $_POST['email'];
            $voucher = $_POST['voucher'];

            $check = "SELECT * FROM `get_pins` where pin = '$voucher' and username='$username'";
            $result = (mysqli_query($conn,$check));
            if ($result->num_rows > 0){

                $token = md5($index."/".$password);
                $date = date("Y-m-d H:i:s");

                $sql ="UPDATE `pins` SET `password`='$password', `mobile`='$mobile', `email`='$email', `active_date`='$date', `token`='$token', status='2'  WHERE (`pin`='$voucher')";
                $update_pin_record = mysqli_query($conn,$sql);
                if ($update_pin_record == TRUE){

                    if (!isset($_COOKIE[$token])){
                        $sql = "INSERT INTO `student_profile`(`token`) VALUES ('$token')";
                        mysqli_query($conn,$sql);
                        $last_id = mysqli_insert_id($conn);
                        setcookie("token",$token,time() + (86400 * 30), "/");
                        if (!isset($_SESSION['token'])){

                            $_SESSION['token'] = $token;
                            $_SESSION['studentID'] = $last_id;
                            $_SESSION['student_name'] = $username;
                            $_SESSION['student_index'] = $index;
                            $_SESSION['password']=$password;
                            //$_USER['picture'] = $user['picture'];

                            header("location: index.php?_route=student&p=profile&e=100");
                        }
                    }else{
                        header("location: index.php?_route=login&e=101");
                    }
                }else{
                    header("location: index.php?_route=register&e=103");
                }
            }else{
                header("location: index.php?_route=register&e=102");
            }
        }
    }

    function login($conn){

        if (!isset($_POST['username'])){
            echo "no user name";
        }else{
            $username = $_POST['username'];
        }

        if (!isset($_POST['password'])){
            echo "no password";
        }else{
            $password =  $_POST['password'];
        }

        $token = md5($username."/".$password);

        $sql = "SELECT * FROM `get_active_pin` where token='$token' LIMIT 1";
        $result = (mysqli_query($conn,$sql));
        if (mysqli_num_rows($result) > 0){
            $user = mysqli_fetch_assoc($result);

            if (!isset($_COOKIE[$token])){
                setcookie("token",$token,time() + (86400 * 30), "/");
                if (!isset($_SESSION['token'])){
                    $_SESSION['token'] = $token;
                    $_SESSION['student_name'] = $user['first_name']." ". $user['surname'];
                    $_SESSION['student_index'] = $username;
                    $_USER['picture'] = $user['picture'];

                    $profile = "SELECT * FROM `student_profile` WHERE token = '$token'";
                    $profile_result = mysqli_query($conn,$profile);
                    if(mysqli_num_rows($profile_result) > 0){
                        $student = mysqli_fetch_assoc($profile_result);
                        $_SESSION['studentID'] = $student['studentID'];
                        $_SESSION['student_name'] = $student['first_name']." ".$student['surname'];
                        if (!isset($student['admissionNo']) OR !isset($student['surname'])){
                            header("location: index.php?_route=student&p=profile&e=100");
                        }else{
                            header("location: index.php?_route=student&p=dashboard&e=100");
                        }
                    }
                }
            }
        }else{
            header("location: index.php");
        }
    }

    function recovery($conn){

        if (!isset($_REQUEST['email'])){
            echo "No email";
        }else{

             $email = $_REQUEST['email'];

            $sql = "SELECT * FROM `get_all_pins` where email='$email' LIMIT 1";
            $result = (mysqli_query($conn,$sql));
            if (mysqli_num_rows($result) > 0){
                $user = mysqli_fetch_assoc($result);
                $_USER['username'] = $user['username'];
                $_USER['password'] = $user['password'];

                $headers = "MIME-Version: 1.0" . "\r\n";
                $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
                $headers .= 'From: <recovery@ghanacu.com>' . "\r\n";

               echo $msg = "username ". $_USER['username'] ."\n Password ". $_USER['password'];
                mail("$email","GhanaCU Login Recovery",$msg,$headers);

                echo "email send";
            }else{
               echo "error";
                // header("location: index.php");
            }
        }
    }
}
