<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 07/11/2018
 * Time: 11:31 AM
 */
class PROFILE{

    function password($conn){

         $id = $_SESSION['studentID'];
        $token = $_SESSION['token'];
        $username = $_POST['username'];
        $password = $_POST['password'];
        $mobile = $_POST['mobile'];
        $email = $_POST['email'];
        $stamp = md5($username."/".$password);

        $sql ="UPDATE `get_all_pins` SET 
            `username` = '$username', 
            `password` = '$password', 
            `mobile` = '$mobile', 
            `email` = '$email', 
            `token` = '$stamp' 
            WHERE `token` = '$token'";
        $result = (mysqli_query($conn,$sql));
        if ($result == TRUE){
            $sql = "UPDATE `student_profile` SET `token` = '$stamp' WHERE `studentID` = '$id'";
            $result = (mysqli_query($conn,$sql));
            if ($result == TRUE){
                $_SESSION['token'] = $stamp;
                setcookie("token",$stamp,time() + (86400 * 30), "/");

                header("location: index.php?_route=student&p=password&e=104");
            }else{
                header("location: index.php?_route=student&p=password&e=103");
            }
        }


    }

    public function add($conn){

        $date= date ("Y-m-d");
        $f_name = $_POST['f-name'];
        $l_name = $_POST['l-name'];
        $dob = $_POST['dob'];
        $marital = $_POST['martial'];
        $nationality = $_POST['nationality'];
        $address = $_POST['address'];
        $admissionNo = $_POST['admission'];
        $gender = $_POST['gender'];
        $mobile = $_POST['mobile-1'];
        $mobile2 =$_POST['mobile-2'];
        $email = $_POST['email'];
        $yearID = $_POST['year'];
        $progID = $_POST['programme'];
        $categoryID = $_POST['category'];
        $stream = $_POST['stream'];
        $campus_status=$_POST['campus_status'];
        $application = $_POST['applicationID'];

        $sql="UPDATE `student_profile` SET 
        `entryID` = '$application', 
        `admissionDate` = '$date', 
        `first_name` = '$f_name', 
        `surname` = '$l_name', 
        `admissionNo` = '$admissionNo', 
        `dob` = '$dob', 
        `gender` = '$gender', 
        `nationalityID` = '$nationality', 
        `marital_status` = '$marital', 
        `mobile1` = '$mobile', 
        `mobile2` = '$mobile2', 
        `email` = '$email', 
        `address` = '$address', 
        `progID` = '$progID', 
        `yearID` = '$yearID', 
        `categoryID` = '$categoryID', 
        `streamID` = '$stream', 
        `campus_status` = '$campus_status', 
        `token` = '12', 
        `statusID` = 21474836472 WHERE `studentID` = 422";
        $result = (mysqli_query($conn,$sql));

        if ($result == TRUE){
            header("location: index.php?_route=student&p=profile&e=104");
        }else{
            header("location: index.php?_route=student&p=profile&e=103");
        }
    }

    public function update($conn){

        $id = $_SESSION['studentID'];
        $date= date ("Y-m-d");
        $f_name = $_POST['f-name'];
        $l_name = $_POST['l-name'];
        $dob = $_POST['dob'];
        $gender = $_POST['gender'];
        $marital = $_POST['marital-status'];
        $nationality = $_POST['nationality'];
        $address = $_POST['address'];
        $admission = $_POST['admission'];
        $mobile = $_POST['mobile-1'];
        $mobile2 =$_POST['mobile-2'];
        $email = $_POST['email'];
        $campus_status = $_POST['hostel'];
        $yearID = $_POST['year'];
        $progID = $_POST['programme'];
        $categoryID = $_POST['category'];
        $stream = $_POST['stream'];
        $application = $_POST['entry'];

        $sql="UPDATE `student_profile` SET 
              `entryID` = '$application',
              `serial_no` = '2', 
              `admissionDate` = '$date',
              `first_name` = '$f_name', 
              `surname` = '$l_name', 
              `admissionNo` = '$admission', 
              `dob` = '$dob',
              `gender` = '$gender',
              `nationalityID` = '$nationality',
              `marital_status` = '$marital',
              `mobile1` = '$mobile',
              `mobile2` = '$mobile2',
              `email` = '$email',
              `address` = '$address',
              `progID` = '$progID',
              `yearID` = '$yearID',
              `categoryID` = '$categoryID',
              `streamID` = '$stream',
              `campus_status` = '$campus_status'
               WHERE `studentID` = '$id'";
        $result = (mysqli_query($conn,$sql));

        if ($result == TRUE){
            header("location: index.php?_route=student&p=profile&e=104");
        }else{
            header("location: index.php?_route=student&p=profile&e=103");
        }
    }

    public function delete(){
        //$id = $_SESSION['studentID'];
    }


}