<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 12/12/2018
 * Time: 6:44 AM
 */

function fees_details($conn){

   $studentID = $_SESSION['studentID'];

    $sql="SELECT * FROM `get_fees_payment_details` WHERE studentID='$studentID' ORDER BY tranNow ASC, tranNow DESC LIMIT 0,1000";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows === 0){
        echo"
                <tr>
                    <td>Null</td>
                    <td>Null</td>
                    <td>Null</td>
                    <td>Null</td>
                    <td>Null</td>
                    <td>Null</td>
                    <td>Null</td>
                </tr>
            ";
    }else{
        while ($r=$result->fetch_assoc()){
            $studentID = $r['studentID'];
            $yearID = $r['yearID'];
            $tran_time = $r['tranNow'];
            $tranDate = $r['tranDate'];

            if($r['semesterID'] = 1){
                $semester = "1st Semester";
            }else{
                $semester = "2nd Semester";
            }

            if(isset($n)){
                $n= $n+1;
            }else{
                $n = 1;
            }

            if(isset($bal)){
                $bal = (($bal + $r['bill'])-$r['paid']);
            }else{
                $bal = $r['bill']-$r['paid'];
            }

            echo"
                <tr>
                    <td>{$n}</td>
                    <td>{$r['tranDate']}</td>
                    <td>{$semester}</td>
                    <td>{$r['yearID']}</td>
                    <td>{$r['ref']}</td>
                    <td>{$r['bill']}</td>
                    <td>{$r['paid']}</td>
                    <td>{$bal}</td>
                </tr>
            ";
        }
    }
}

function hostel_details($conn){

    $studentID = $_SESSION['studentID'];

    $sql="SELECT * FROM `get_hostel_booking_details` where studentID='$studentID'";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows > 0){
        while ($r=$result->fetch_assoc()){
            $room = $r['block_name']."-".$r['room'];
            $yearID = $r['yearID'];
            $in = $r['book_in'];

            if (!isset($out)){
                $out ="Not Out";
            }else{
                $out = $r['book_out'];
            }

            echo"
                <tr>
                    <td>{$yearID}</td>
                    <td>{$room}</td>
                    <td>{$in}</td>
                    <td>{$out}</td>
                </tr>";
        }
    }
}

function enrollment_details($conn){

    $studentID = $_SESSION['studentID'];

    $sql="SELECT * FROM `get_student_enrollment` where studentID='$studentID' and statusID='2'";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows > 0){
        while ($r=$result->fetch_assoc()){
            $yearID = $r['yearID'];
            $programme =  $r['prefix']."/".$r['programme'];
            $semester = $r['semesterID'];
            $school = $r['prefix'];
            $admission = $r['stud_index'];
            $level = $r['s_level'];
            $name = $r['name'];

            if($semester == 1){
                $sem = "1st Semester";
            }elseif ($semester == 2){
                $sem = "2nd Semester";
            }else{
                $sem = "Unknown";
            }
            echo"
                <tr>
                    <td>{$yearID}</td>
                    <td>{$programme}</td>
                    <td>{$sem}</td>
                    <td>{$level}</td>
                    <td><a href='index.php?_route=student&p=course.registration&d={$r['progID']}&st={$studentID}&l={$level}&s={$semester}&sch={$school}&adm={$admission}&y={$yearID}'>Courses</a></td>
                </tr>";
        }
    }
}

function get_course_registered($conn){

    $studentID = $_SESSION['studentID'];
    $year = $_GET['y'];
    $semesterID = $_GET['s'];

    $sql="SELECT * FROM `get_course_registrated` where studentID='$studentID' and yearID='$year' and semesterID='$semesterID'";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows > 0){
        while ($r=$result->fetch_assoc()){
            echo"
                <tr>
                    <td>{$r['course_code']}</td>
                    <td>{$r['course']}</td>
                    <td>{$r['credit']}</td>
                    <td>{$r['stud_index']}</td>
                    <td><a href='index.php?submit=remove.reg.course&d={$r['regID']}'>Remove</a></td>
                    <td></td>
                </tr>";

        }
    }
}

function manage_ticket($conn){

    $sql="SELECT * FROM `get_ticket` LIMIT 0, 10";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows === 0){

    }else{
        while ($r = $result->fetch_assoc()){
            if($r['statusID'] == 1){
                $status = "Resolve Issue";
            }elseif ($r['statusID'] == 2){
                $status = "Close Issue";
            }

            echo"
                <div class='row ticket-card mt-3 pb-2 border-bottom pb-3 mb-3'>
                    <div class='col-md-1'>
                        <img class='img-sm rounded-circle mb-4 mb-md-0' src='asset/images/faces/face1.jpg' alt='profile image'>
                    </div>
                    <div class='ticket-details col-md-9'>
                        <div class='d-flex'>
                            <p class='text-dark font-weight-semibold mr-2 mb-0 no-wrap'>{$r['user']} :</p>
                            <p class='text-primary mr-1 mb-0'>[#{$r['ticket_no']}]</p>
                            <p class='mb-0 ellipsis'>{$r['subject']}</p>
                        </div>
                        <p class='text-gray ellipsis mb-2'>{$r['ticket_note']}</p>
                        <div class='row text-gray d-md-flex d-none'>
                            <div class='col-4 d-flex'>
                                <small class='mb-0 mr-2 text-muted text-muted'>Date :</small>
                                <small class='Last-responded mr-2 mb-0 text-muted text-muted'>{$r['ticket_date']}</small>
                            </div>
                        </div>
                    </div>
                    <div class='ticket-actions col-md-2'>
                        <div class='btn-group dropdown'>
                            <button type='button' class='btn btn-success btn-sm' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
                                {$status}
                            </button>
                        </div>
                    </div>
                </div>
            ";
        }
    }
}

function school_fees_bill_details($conn,$academic,$programmeID,$semesterID){

   $catID = $_SESSION['studentCatID'];

    $sql="SELECT * FROM `get_programme` where `progID`='$programmeID' LIMIT 0, 1";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows > 0){
        $r=$result->fetch_assoc();
        $schoolID = $r['schoolID'];
    }else{
        $schoolID =null;
    }

    echo $sql="SELECT * FROM `get_fees_bill` where `semesterID`='$semesterID' and `school_ID`='$schoolID' and `catID`='$catID' LIMIT 0, 1";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows > 0){
        while ($r=$result->fetch_assoc()){
            $tf = $r['tf'];
            $fuf =  $r['fuf'];
            $src = $r['src'];
            $fdf = $r['fdf'];
            $af = $r['af'];
            $rv = $r['rv'];
            $mat = $r['matr'];
            $med = $r['medi'];
            $shb = $r['shb'];
            $other = $r['other'];
            $semester = $r['semesterID'];
            $amount = $r['amount'];

            if($semester == 1){
                $sem = "1st Semester";
            }elseif ($semester == 2){
                $sem = "2nd Semester";
            }else{
                $sem = "Unknown";
            }
            echo"
                <tr>
                    <td>Tuition Fees</td>
                    <td>{$tf}</td>
                </tr>
                <tr>
                    <td>Facility User Fees</td>
                    <td>{$fuf}</td>
                </tr>
                <tr>
                    <td>SRC-Fees</td>
                    <td>{$src}</td>
                </tr>
                <tr>
                    <td>Facility Due Fees</td>
                    <td>{$fdf}</td>
                </tr>
                <tr>
                    <td>Acceptance Fees</td>
                    <td>{$af}</td>
                </tr>
                <tr>
                    <td>Result Verification</td>
                    <td>{$rv}</td>
                </tr>
                <tr>
                    <td></td>
                    <td>{$mat}</td>
                </tr>
                <tr>
                    <td>Medical Examination</td>
                    <td>{$med}</td>
                </tr>
                <tr>
                    <td>Student Hand book</td>
                    <td>{$shb}</td>
                </tr>
                <tr>
                    <td>Other Fees</td>
                    <td>{$other}</td>
                </tr>
                <tr>
                    <td>Total</td>
                    <td>{$amount}</td>
                </tr>
                ";
        }
    }
}

?>

