<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 12/12/2018
 * Time: 6:44 AM
 */



function fees_details($conn){

   $studentID = $_SESSION['student_index_id'];

    $sql="SELECT * FROM `get_fees_payment_details` WHERE studentID='$studentID' ORDER BY feeID DESC, tranNow DESC LIMIT 0,1000";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows === 0){
        echo"
                <tr>
                    <td>Null</td>
                    <td>Null</td>
                    <td>Null</td>
                    <td>Null</td>
                    <td>Null</td>
                    <td>Null</td>
                    <td>Null</td>
                </tr>
            ";
    }else{
        while ($r=$result->fetch_assoc()){
            $studentID = $r['studentID'];
            $yearID = $r['yearID'];
            $tran_time = $r['tranNow'];
            $tranDate = $r['tranDate'];

            if($r['semesterID'] = 1){
                $semester = "1st Semester";
            }else{
                $semester = "2nd Semester";
            }

            echo"
                <tr>
                    <td>{$r['ref_index']}</td>
                    <td>{$r['tranDate']}</td>
                    <td>{$semester}</td>
                    <td>{$r['yearID']}</td>
                    <td>{$r['ref']}</td>
                    <td>{$r['bill']}</td>
                    <td>{$r['paid']}</td>
                </tr>
            ";
        }
    }
}

function hostel_details($conn){

    $studentID = $_SESSION['student_index'];

    $sql="SELECT * FROM `get_hostel_booking_details` where studentID='$studentID'";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows > 0){
        while ($r=$result->fetch_assoc()){
            $room = $r['block_name']."-".$r['room'];
            $yearID = $r['yearID'];
            $in = $r['book_in'];

            if (!isset($out)){
                $out ="Not Out";
            }else{
                $out = $r['book_out'];
            }

            echo"
                <tr>
                    <td>{$yearID}</td>
                    <td>{$room}</td>
                    <td>{$in}</td>
                    <td>{$out}</td>
                </tr>";
        }
    }
}



function enrollment_details($conn){

    $studentID = $_SESSION['student_index'];

    $sql="SELECT * FROM `get_student_enrollment` where stud_index='$studentID' and statusID='2'";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows > 0){
        while ($r=$result->fetch_assoc()){
            $yearID = $r['yearID'];
            $programme =  $r['prefix']."/".$r['programme'];
            $semester = $r['semesterID'];
            $school = $r['prefix'];
            $admission = $r['stud_index'];
            $level = $r['s_level'];
            $name = $r['name'];

            if($semester == 1){
                $sem = "1st Semester";
            }elseif ($semester == 2){
                $sem = "2nd Semester";
            }else{
                $sem = "Unknown";
            }
            echo"
                <tr>
                    <td>{$yearID}</td>
                    <td>{$programme}</td>
                    <td>{$sem}</td>
                    <td>{$level}</td>
                    <td><a href='index.php?_route=student&p=course.registration&d={$r['progID']}&st={$studentID}&l={$level}&s={$semester}&sch={$school}&adm={$admission}&y={$yearID}'>Courses</a></td>
                </tr>";
        }
    }
}

function get_course_registered($conn){

    $studentID = $_SESSION['student_index_id'];
    $year = $_GET['y'];
    $semesterID = $_GET['s'];

    $sql="SELECT * FROM `get_course_registrated` where studentID='$studentID' and yearID='$year' and semesterID='$semesterID'";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows > 0){
        while ($r=$result->fetch_assoc()){
            echo"
                <tr>
                    <td>{$r['course_code']}</td>
                    <td>{$r['course']}</td>
                    <td>{$r['credit']}</td>
                    <td>{$r['stud_index']}</td>
                    <td><a href='index.php?submit=remove.reg.course&d={$r['regID']}'>Remove</a></td>
                    <td></td>
                </tr>";

        }
    }
}
