<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 12/12/2018
 * Time: 6:44 AM
 */



function fees_details($conn){

    $sql="SELECT * FROM `school_data`.`get_fees_payment_details` LIMIT 0,1000";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows > 0){
        $r=$result->fetch_assoc();

        $studentID = $r['studentID'];
        $yearID = $r['yearID'];
        $tran_time = $r['tran_time'];
        $tranDate = $r['tranDate'];


        echo"
        <tr>
            <td>{$r['first_name']} {$r['surname']}</td>
            <td>{{$r['yearID']}}</td>
            <td>{{$r['yearID']}}</td>
            <td>{{$r['yearID']}}</td>
            <td>{{$r['yearID']}}</td>
            <td>{{$r['yearID']}}</td>
        </tr>
    ";
    }
}

function hostel_details($conn){

    $studentID = $_SESSION['studentID'];

    $sql="SELECT * FROM `school_data`.`get_hostel_booking_details` where studentID='$studentID'";
    $result = mysqli_query($conn,$sql);
    if ($result->num_rows > 0){
        while ($r=$result->fetch_assoc()){
            $room = $r['block_name']."-".$r['room'];
            $yearID = $r['yearID'];
            $in = $r['book_in'];

            if (!isset($out)){
                $out ="Not Out";
            }else{
                $out = $r['book_out'];
            }

            echo"
        <tr>
            <td>{$yearID}</td>
            <td>{$room}</td>
            <td>{$in}</td>
            <td>{$out}</td>
        </tr>";
        }
    }

}